version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
      time: '09:00'
      timezone: 'Europe/Madrid'
    open-pull-requests-limit: 10
    groups:
      eslint:
        patterns:
          - '@shlinkio/eslint-config-js-coding-standard'
          - 'typescript-eslint'
          - '*eslint-plugin*'
          - eslint
      shlink:
        patterns:
          - '@shlinkio/*'
      testing:
        patterns:
          - '@testing-library/*'
      vite:
        patterns:
          - 'vite'
          - 'vite-plugin-dts'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'
